backend:
  name: github
  repo: thisiscapra/thisiscapra.com # Path to your GitHub repository
  branch: staging # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "source/images/uploads"
public_folder: "source"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "source/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    sort: "date:asc" # Default is title:asc
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post-layout"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "work" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Work" # Used in the UI, ie.: "New Post"
    folder: "source/work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    sort: "date:asc" # Default is title:asc
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Sub Title", name: "sub_title", widget: "string"}
      - {label: "Project Intro", name: "body", widget: "markdown"}
      - label: "What we did" 
        name: "what_we_did"
        widget: "list"
        fields:
          - {label: "Item", name: "item", widget: "list"}
      - {label: "Sub content", name: "sub_content", widget: "markdown", required: false}
      - {label: "Testimonial", name: "testimonial", widget: "string", required: false}
      - {label: "Featured Testimonial", name: "featured_testimonial", widget: "string", required: false}
      - {label: "Cite", name: "cite", widget: "string", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - label: "Gallery"
        name: "gallery" 
        widget: "list"
        fields:
          - {label: "Gallery Image", name: "gallery_image", widget: "image"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio-layout"}